# Generated by Django 3.2.6 on 2021-08-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0002_auto_20210827_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'Testimonial Table'},
        ),
    ]
