# Generated by Django 3.2.6 on 2021-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveIntegerField(max_length=12)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Reservation Table',
            },
        ),
    ]
