# Generated by Django 3.2.6 on 2021-08-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0005_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
