# Generated by Django 3.2.6 on 2021-08-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
