# Generated by Django 3.2.6 on 2021-08-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0008_alter_reservation_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='Password',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
