# Generated by Django 3.2.6 on 2021-08-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0009_auto_20210831_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Password',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
