# Generated by Django 3.2.6 on 2021-09-02 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0010_auto_20210831_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('invoice_id', models.CharField(blank=True, max_length=100)),
                ('payer_id', models.CharField(blank=True, max_length=100)),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.profile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP1.dishes')),
            ],
            options={
                'verbose_name_plural': 'Order Table',
            },
        ),
    ]
