# Generated by Django 3.2.6 on 2021-09-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0013_auto_20210903_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(upload_to='dishes'),
        ),
    ]
